### ISSUE TITLE
Website Image Size Too Small

### ISSUE THREAD

**Issue by TTangNingzhi** [codegrits/CodeGRITS#2]
I adjust the size of the images by the visual effect on my large monitor, but it seems that the size is too small on my
laptop. Using the following code snippets does not work well, please fix it.
```html
<div style="text-align: center;">
    <img src="imgs/visualization.png" style="width: 80%;"><br><br>
</div>
```

**Comment by TTangNingzhi** [comment]
Only `welcome.md` and `usage.md` have images.

**Comment by wanteatfruit** [comment]
Changed img style to `max-width:100%; height: auto;` for responsive size adjustment.

**Comment by TTangNingzhi** [comment]
Use a mix of `width` and `max-width` to control the size of the image. For example, `<img src="static/overview.png" style="width: 100%; max-width: 600px; height: auto;">`.
